FROM oraclelinux:7-slim

ADD oracle-instantclient*.rpm /tmp/

RUN  yum -y install /tmp/oracle-instantclient*.rpm && \
    rm -rf /var/cache/yum && \
    rm -f /tmp/oracle-instantclient*.rpm && \
    echo /usr/lib/oracle/12.2/client64/lib > /etc/ld.so.conf.d/oracle-instantclient12.2.conf && \
    ldconfig

ENV PATH=$PATH:/usr/lib/oracle/12.2/client64/bin

CMD  ["sqlplus", "-v"]
ENTRYPOINT ["tail", "-f", "/dev/null" ]
